[package]
name = "evalex"
version = "0.1.0-alpha"
authors = ["Fabrizio Sestito <fabrizio.sestito@suse.com>"]
edition = "2018"

[lib]
name = "evalex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
evalexpr = { version = "8.1.0", features = ["regex_support"] }
