[package]
name = "evalex"
version = "0.2.0-dev"
authors = ["Fabrizio Sestito <fabrizio.sestito@suse.com>"]
edition = "2018"

[lib]
name = "evalex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
evalexpr = { version = "11.3.0", features = ["regex_support"] }
