[package]
name = "evalexpr_rustler"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "evalexpr_rustler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
evalexpr = { version = "8.1.0", features = ["regex_support"] }
